version: '3'

services:
  library:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    restart: on-failure
    volumes:
      - ./lib:/app/lib:delegated
      - ./zok:/app/zok:delegated
    command: tail -F /dev/null

  ganache:
    image: trufflesuite/ganache-cli
