name: Release

on:
  push:
    branches:
      - master
      - beta
      - alpha

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: http://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm ci

      # - name: Validate before release
      #   run: npm run lint

      - name: Release
        run: |
         echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
         npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
