name: Validate Code

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [10.x, 11.x, 12.x]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install --no-save
      # - run: npm run lint
      # - run: npm run lint:md
      - run: npm run test
